### PR TITLE
Grant button doesn't help when user gets an error in SQL Server

### PR DESCRIPTION
**Pull request by sergey-solomentsev-nemetos**
When SIM user clicks next on Permission step he gets this message: 

> You probably don't have necessary permissions set. Please try to click 'Grant' button before you proceed.

Trying to click "Grant" button doesn't do anything if `SqlServerManager.Instance.TestSqlServer` fails in `Permissions.OnMovingNext` method i.e. with this message:

> CREATE DATABASE permission denied in database 'master'.

`SqlServerManager.Instance.TestSqlServer` returns false and message suggests to SIM user to click "Grant" button again, which doesn't make sense,

 So I would recommend to move calling of `TestSqlServer` method to the `ConnectionString.OnMovingNext` method or to change message to more appropriate.

### CODE REVIEW

**Comment by AlenPelin** [comment]
Hi @sergey-solomentsev-nemetos, thanks for your contribution here and sorry for a long delay. Could you please describe in detail what is the business purpose of this fix taking into account that this functionality is disabled by default?

**Comment by sergey-solomentsev-nemetos** [comment]
Hi @AlenPelin , thank you for your response.

Here is scenario without fix:

1. I've created a new user without providing any permissions to it
new-user
2. Then launched SIM and got the Initial Configuration Wizard;
3. Proceeded to the fifth step of the wizard presented on "ConnectionString.xaml";
4. Put this connection setting: "Data Source=.;User ID=new-sim-test;Password=asd123456"
image

5. Clicked "Next";
6. On the sixth step and clicked Grant button;
7. Clicked "Next" and got error message 
error-message

8. Repeated steps 6-7.


With this fix by clicking next on the fifth step of the wizard (see №5 in scenario above) User will get this message:

permission-denied-message

**Comment by sergey-solomentsev-nemetos** [comment]
Hi @AlenPelin , as I can see, error message indicating described problem has been improved. Code in this pull request is outdated, closing this pull request.

**Comment by AlenPelin** [comment]
Thanks for an update. I am glad that current version gives enough background info.

**Pull request closed without merging**
