### PR TITLE
Add manifest for Solr Support Package 2.0.0, used by Sitecore XP 8.2

### PR DESCRIPTION
**Pull request by dsolovay**
Sitecore 8.2 shipped with a new Solr Support package, which no longer modified Global.asax. This is supported by a new manifest. In addition, I have added logic to bypass enabling SOLR "IOC" files, and to avoid disabling Lucene default configuration files.

### CODE REVIEW

**Comment by dsolovay** [comment]
I have tested against 8.1 (with `Sitecore.Solr.Support 1.0.0 rev 160504`) and 8.2 (with `Sitecore.Solr.Support 2.0.0 rev 160726`) and both work cleanly.

Still open is enabling term support, which I just discovered in the [documentation](https://doc.sitecore.net/sitecore_experience_platform/80/setting_up__maintaining/search_and_indexing/walkthrough_setting_up_solr#_Toc399318998). This is required for some UI features.  I have opened an issue,  dsolovay/sitecore-instance-manager#38, to track this, and will get to it shortly.

**Comment by AlenPelin** [comment]
@dsolovay Why is it still required to download support package? AFAIK 8.2 already includes everything required to work with SOLR and only action we need to do is enable necessary bundled configs.

**Comment by dsolovay** [comment]
@AlenPelin Sitecore 8.2 no longer requires DI containers or changes to global.asax, but does still require a support package available on the 8.2 download [site](https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform/82/Sitecore_Experience_Platform_82_Initial_Release.aspx). The package contains the Solr specific DLLs, such as Sitecore.ContentSearch.Solr.dll, which are not shipped with the main product. 

In addition to enabling the Solr configs, it is necessary to configure and create the Solr cores, as well as disabling the Lucene configs.

**Comment by AlenPelin** [comment]
> but does still require a support package available on the 8.2 download site. The package contains the Solr specific DLLs, such as Sitecore.ContentSearch.Solr.dll, which are not shipped with the main product.

I have reviewed the solr support package and it contains only DI implementation for backwards compatibility. Our product team has confirmed that it is no longer required for new installations.

**Comment by dsolovay** [comment]
@AlenPelin, my mistake. I checked again, and you and the product team are of course correct. My bad answering on my iPhone, without going back to Visual Studio. :-1: 

However, that leaves open the question of what to do with the automation that was driven by the manifest. This saves the user a number of manual steps:
* It disables the Lucene files and enabled the Solr ones.
* It applies a SIM-like naming convention to the Solr core names (e.g. sc82u0_sitecore_master_index), preventing collisions if a user has multiple sites supported by a single Solr endpoint.
* It allows the user to change the Solr endpoint URL from http://localhost:8983/solr.
* It creates a solr instanceDir directory for each configured index.
* It applies the "Generate the Solr Schema.xml file" step for each configured index.
* It call the Solr API to create each configured index.

There seems a lot of value here, and the automation is in keeping with the way that SIM works for other features (e.g Database creation).  I recommend I move this to a Configuration Preset, create an empty zip file `Configuration - Sitecore 8 - Content Search - Solr.zip` and move the new functionality to `Configuration - Sitecore 8 - Content Search - Solr.zip.manifest`.  

Good approach?

**Comment by AlenPelin** [comment]
Agree, `Configuration - Sitecore 8.2 - Content Search - Enable Solr` looks good. Important, when SIM sees Sitecore 8.2 it automatically hides this option for non-8.2 setups, however it does not support 8.2+ so lets stick to exactly 8.2.

**Comment by dsolovay** [comment]
Changes made.

**Comment by AlenPelin** [comment]
@dsolovay great job! I'd appreciate if you could record short video (silent if you want) that demonstrates how to use that e.g. download solr, set it up, install a sitecore instance and configure it to use solr, delete lucene indexes, show search works.

**Comment by dsolovay** [comment]
Will do. Was on my to do list, but this moved it up!

**Pull request merged**
